services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=tajedin
      - MYSQL_DATABASE=Test_Grafana
      - MYSQL_PASSWORD=tajedin
    volumes:
      - MySql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - main

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "1111:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: tajedin
    networks:
      - main
  
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - main
    depends_on:
      - db
    environment:
      - GF_DATASOURCE = mysql://tajedin:tajedin@main:3306

volumes:
  MySql_db:
  grafana-data:

networks:
  main: